name: Expose Android app version
description: Finds the version code and version name in your build.gradle.kts file and set them as environment variables.
author: Maria Ivanovskaya
branding:
  icon: 'at-sign'
  color: 'orange'
inputs:
  EXPOSE_CODE:
    description: 'Specify whether to expose the version code'
    required: false
    default: 'true'
  EXPOSE_NAME:
    description: 'Specify whether to expose the version name'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set executable permission for the script
      run: chmod +x $GITHUB_WORKSPACE/extract-expose-version.sh
      shell: bash

    - name: Run the script with inputs
      run: |
        export IN_EXPOSE_CODE="${{ inputs.EXPOSE_CODE }}"
        export IN_EXPOSE_NAME="${{ inputs.EXPOSE_NAME }}"
        if [[ $IN_EXPOSE_CODE == "false" && $IN_EXPOSE_NAME == "false" ]]; then
          echo "Both EXPOSE_CODE and EXPOSE_NAME are set to false. Skipping further steps."
          echo "skip_steps=true" >> $GITHUB_ENV
        else
          echo "skip_steps=false" >> $GITHUB_ENV
        fi
        $GITHUB_WORKSPACE/extract-expose-version.sh $IN_EXPOSE_CODE $IN_EXPOSE_NAME
      shell: bash

    - name: Read extracted values from file
      if: ${{ !cancelled() && env.skip_steps != 'true' }}
      id: read_values
      run: cat extracted_values.txt
      shell: bash

    - name: Set environment variables
      if: ${{ !cancelled() && env.skip_steps != 'true' }}
      run: |
        if grep -q "ANDROID_VERSION_CODE" extracted_values.txt; then
          ANDROID_VERSION_CODE=$(grep "ANDROID_VERSION_CODE" extracted_values.txt | cut -d '=' -f 2 | tr -d '[:space:]')
          ANDROID_VERSION_CODE_STR="$ANDROID_VERSION_CODE"
          echo "ANDROID_VERSION_CODE=$ANDROID_VERSION_CODE_STR" >> $GITHUB_ENV
        fi

        if grep -q "ANDROID_VERSION_NAME" extracted_values.txt; then
          ANDROID_VERSION_NAME=$(grep "ANDROID_VERSION_NAME" extracted_values.txt | cut -d '=' -f 2 | tr -d '[:space:]')
          echo "ANDROID_VERSION_NAME=$ANDROID_VERSION_NAME" >> $GITHUB_ENV
        fi
      shell: bash
