name: Test Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create mock build.gradle.kts
        run: |
          mkdir -p app
          echo "android {" > app/build.gradle.kts
          echo "    defaultConfig {" >> app/build.gradle.kts
          echo "        versionName = \"4.22.0\"" >> app/build.gradle.kts
          echo "        versionCode = 123" >> app/build.gradle.kts
          echo "    }" >> app/build.gradle.kts
          echo "}" >> app/build.gradle.kts

      - name: Run action
        uses: ./
        with:
          EXPOSE_CODE: 'true'
          EXPOSE_NAME: 'true'

      - name: Validate versionName and versionCode
        run: |
          content=$(cat app/build.gradle.kts)
          if [[ $content == *"versionName = \"4.22.0\""* && $content == *"versionCode = 123"* ]]; then
            echo "Mock build.gradle.kts contains versionName and versionCode, NAME is $ANDROID_VERSION_NAME, CODE is $ANDROID_VERSION_CODE"
          else
            echo "Mock build.gradle.kts does not contain expected values"
            exit 1
          fi

      - name: Verify Environment Variables
        run: |
          echo "ANDROID_VERSION_NAME: $ANDROID_VERSION_NAME"
          echo "ANDROID_VERSION_CODE: $ANDROID_VERSION_CODE"
          if [[ $ANDROID_VERSION_NAME == 4.22.0 && $ANDROID_VERSION_CODE == 123 ]]; then
            echo "Environment variables are set correctly."
          else
            echo "Environment variables are not set as expected."
            exit 1
          fi
